### ISSUE TITLE
Replace DeltaSpike snapshot version with a stable one

### ISSUE THREAD

**Issue by mshabarov** [vaadin/cdi#414]
CDI 15.0 is Jakarta EE 9.0 compatible, but it uses DeltaSpike [1.9.7-SNAPSHOT](https://github.com/vaadin/cdi/blob/44a2598f5125ebbfda9854dfc762c0c770c5545a/pom.xml#L50) version.
The stable version is requested in this [ticket](https://issues.apache.org/jira/browse/DELTASPIKE-1434), but the release date is unknown.
Possible solutions are:
- do the conversion by ourselves and include https://github.com/apache/deltaspike sources into CDI add-on,
- fork from https://github.com/apache/deltaspike , convert and release `com.vaadin.external.*` version,
- replace with Jakarta EE 9.0 compatible implementation, like for instance, this [community ported version](https://github.com/atbashEE/deltaspike-jakarta).

**Comment by mshabarov** [comment]
DeltaSpike 1.9.7 is not compatible with `cdi-api` version 4.0.1 (Jakarta EE 10 part), works fine with `cdi-api` 3.0.1 though (EE 9)
```
            <dependency>
                <groupId>jakarta.enterprise</groupId>
                <artifactId>jakarta.enterprise.cdi-api</artifactId>
                <version>4.0.1</version>
            </dependency>
```
BeanManager tries to use removed method in EE 10:
```
java.lang.NoSuchMethodError: 'jakarta.enterprise.inject.spi.InjectionTarget jakarta.enterprise.inject.spi.BeanManager.createInjectionTarget(jakarta.enterprise.inject.spi.AnnotatedType)'
at org.apache.deltaspike.core.api.provider.BeanProvider.injectFields(BeanProvider.java:472)
at org.apache.deltaspike.testcontrol.api.junit.CdiTestRunner.createTest(CdiTestRunner.java:210)
```
Not only we need a stable version, but also a patch to use the new API.

**Comment by MarcinVaadin** [comment]
The bigger problem is that there are multiple usages of BeanManager from 3rd party libs like openejb, weld and they all need to be updated to use jakarta instead of javax.

**Comment by mshabarov** [comment]
If I recall correctly, in a current impl of Flow CDI we just transform the javax to jakarta and produce the new artifact to build our Flow CDI classes with. I assume we should do the transformation manually for the forked DeltaSpike and probably update 3rd parties to a newer Jakarta-compatible versions, yes.

**Comment by MarcinVaadin** [comment]
It is worth mentioning that OpenWebBeans support has also been dropped due to Jakarta 10 / CDI 4.0 incompatibilities. CDI now uses Weld as CDI container.
